name: Daily eBay Scraper

on:
  schedule:
    - cron: '0 13 * * *'  # Every day at 9AM Eastern (13:00 UTC)
  workflow_dispatch:       # Enables manual trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run eBay scraper
        run: python ebay_scraper.py

      - name: Commit updated CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.csv
          git commit -m "Automated scrape results [$(date)]" || echo "No changes to commit"
          git push
